-- P4.1 -- content access state, Credit price and age floor, on the P0.8 offer.
--
-- Generated by drizzle-kit, then its state conversion written out by hand:
-- drizzle casts the old values straight to the new type, which fails on any
-- existing `locked`, `paid` or `retired` offer. The resulting schema is exactly
-- the generated snapshot's.
--
-- THE MAPPING (P0.8 -> P4.1), for any offer that exists. None should: P0.8
-- refuses every offer write while the economy is off, and no route writes one.
--   free    -> free
--   locked  -> premium       (access conditional on Premium)
--   paid    -> unavailable   (no price exists to make it `credit`: fail closed,
--                             never free)
--   retired -> unavailable   (its earlier state was not kept; `retired_at` still
--                             marks it as no longer live)
-- Content with no offer is untouched and stays FREE: nothing is backfilled.
ALTER TABLE "content_offers" DROP CONSTRAINT "content_offers_retired_consistent";--> statement-breakpoint
ALTER TABLE "content_offers" ALTER COLUMN "state" DROP DEFAULT;--> statement-breakpoint
ALTER TYPE "public"."commercial_state" RENAME TO "commercial_state_p08";--> statement-breakpoint
CREATE TYPE "public"."commercial_state" AS ENUM('free', 'premium', 'credit', 'unavailable');--> statement-breakpoint
ALTER TABLE "content_offers" ALTER COLUMN "state" SET DATA TYPE "public"."commercial_state" USING (
  CASE "state"::text
    WHEN 'free' THEN 'free'
    WHEN 'locked' THEN 'premium'
    ELSE 'unavailable'
  END
)::"public"."commercial_state";--> statement-breakpoint
ALTER TABLE "content_offers" ALTER COLUMN "state" SET DEFAULT 'free'::"public"."commercial_state";--> statement-breakpoint
DROP TYPE "public"."commercial_state_p08";--> statement-breakpoint
ALTER TABLE "content_offers" ADD COLUMN "credit_price" integer;--> statement-breakpoint
ALTER TABLE "content_offers" ADD COLUMN "age_floor" integer;--> statement-breakpoint
ALTER TABLE "content_offers" ADD CONSTRAINT "content_offers_credit_price" CHECK (("content_offers"."state" = 'credit') = ("content_offers"."credit_price" is not null));--> statement-breakpoint
ALTER TABLE "content_offers" ADD CONSTRAINT "content_offers_credit_price_positive" CHECK ("content_offers"."credit_price" is null or "content_offers"."credit_price" > 0);--> statement-breakpoint
ALTER TABLE "content_offers" ADD CONSTRAINT "content_offers_age_floor" CHECK ("content_offers"."age_floor" is null or "content_offers"."age_floor" between 18 and 99);
