import { randomUUID } from 'node:crypto';
import { existsSync } from 'node:fs';
import { join, relative } from 'node:path';
import type { Db } from '../db/client.js';
import type { CharacterVisualAssetRow } from '../db/schema.js';
import { CostLedger } from '../media-pipeline/cost-ledger.js';
import { ProviderError, type MediaProviders } from '../media-pipeline/types.js';
import {
  createVisualAsset,
  getVisualAssetById,
  type ContentRating,
  type VisualAssetStatus,
} from './visual-asset-service.js';
import { getActiveVisualIdentity } from './visual-identity-service.js';
import { GENERATED_ASSET_STATUS } from '../generation/config.js';

/**
 * Media generation job service (US-36 PoC).
 *
 * The single place that connects the offline provider seam (Atlas/mock) to the
 * durable data model: it runs a provider generation, saves the bytes under the
 * per-character storage tree, and records a `character_visual_assets` row with
 * provenance + content_rating + a non-canonical status. Nothing here knows the
 * vendor — it receives resolved `MediaProviders`.
 *
 * Design guarantees (from the ticket + repo rules):
 *  - is_canonical is NEVER set here — createVisualAsset always inserts false,
 *    and promotion stays an explicit, separate approval action.
 *  - content_rating is DATA carried through from the request (or inherited from
 *    the source asset for video), never a separate code path.
 *  - The prompt is passed through from the caller; no content is baked in.
 *  - A provider failure is caught, its estimated cost is still recorded (a
 *    failed paid attempt is never assumed free), a structured reason is
 *    returned, and the process never crashes. Exactly ONE provider attempt per
 *    request — retry is a new request, so there is no unbounded retry loop.
 */

export interface MediaStorageConfig {
  /** Root directory generated bytes are written under. */
  storageDir: string;
  /** When set, storage_key becomes `${publicBaseUrl}/<relpath>`; else the path. */
  publicBaseUrl: string | null;
}

export interface MediaJobDeps {
  providers: MediaProviders;
  ledger: CostLedger;
  storage: MediaStorageConfig;
  /** Optional per-character budget passed to the ledger authorization. */
  characterBudgetUsd?: number;
}

export interface GenerateImageInput {
  characterId: string;
  prompt: string;
  /** Optional identity-consistent reference (must be a locally-stored asset). */
  referenceAssetId?: string;
  contentRating?: ContentRating;
  /** Initial lifecycle status; defaults to `under_review` (US-105 / EPIC 11:
   * generation never makes content live). Never canonical. */
  status?: Extract<VisualAssetStatus, 'generated' | 'under_review'>;
  /**
   * The content requirement this asset is meant to satisfy. Written straight
   * onto the asset, so generated content reaches Review already filed under
   * its category instead of landing in triage.
   */
  requirementKey?: string | null;
  width?: number;
  height?: number;
}

export interface GenerateVideoInput {
  characterId: string;
  /** Source still to animate (image-to-video). Must be a locally-stored asset. */
  sourceImageAssetId: string;
  motionPrompt: string;
  /** Target ~5–8s; defaults to 5. */
  durationSeconds?: number;
  resolution?: '480p' | '720p' | '1080p';
  /** Overrides the rating inherited from the source asset. */
  contentRating?: ContentRating;
  status?: Extract<VisualAssetStatus, 'generated' | 'under_review'>;
  /**
   * The content requirement this asset is meant to satisfy. Written straight
   * onto the asset, so generated content reaches Review already filed under
   * its category instead of landing in triage.
   */
  requirementKey?: string | null;
}

export interface MediaJobCost {
  estimatedCostUsd: number;
  cumulativeUsd: number;
}

export type MediaJobResult =
  | { ok: true; jobId: string; asset: CharacterVisualAssetRow; cost: MediaJobCost }
  | { ok: false; jobId: string; error: { kind: string; message: string } };

/** storage_key is the public URL when a base is configured, else the raw path. */
function toStorageKey(storage: MediaStorageConfig, outputPath: string): string {
  if (!storage.publicBaseUrl) return outputPath;
  const rel = relative(storage.storageDir, outputPath).split('\\').join('/');
  return `${storage.publicBaseUrl.replace(/\/+$/, '')}/${rel}`;
}

/** The server-side local path of a previously-generated asset, if we have one. */
function localPathOf(asset: CharacterVisualAssetRow): string | null {
  const p = (asset.provenance as Record<string, unknown>).storagePath;
  return typeof p === 'string' && p.length > 0 ? p : null;
}

function outputPathFor(storageDir: string, characterId: string, jobId: string, ext: string): string {
  return join(storageDir, characterId, 'generated', `${jobId}.${ext}`);
}

function errorFrom(err: unknown): { kind: string; message: string } {
  if (err instanceof ProviderError) return { kind: err.kind, message: err.message };
  return { kind: 'unknown', message: err instanceof Error ? err.message : String(err) };
}

/**
 * Generate one image for a character and persist it as a generated visual asset.
 * Returns a structured result — success carries the asset row; failure carries a
 * reason and never throws to the caller.
 */
export async function generateImageJob(
  db: Db,
  deps: MediaJobDeps,
  input: GenerateImageInput,
): Promise<MediaJobResult> {
  const jobId = randomUUID();

  const identity = await getActiveVisualIdentity(db, input.characterId);
  if (!identity) {
    return {
      ok: false,
      jobId,
      error: { kind: 'no_active_identity', message: 'character has no active visual identity to attach the asset to' },
    };
  }

  // Optional reference must be a locally-stored asset belonging to this character.
  let referenceImagePath: string | undefined;
  if (input.referenceAssetId) {
    const ref = await getVisualAssetById(db, input.referenceAssetId);
    if (!ref || ref.characterId !== input.characterId) {
      return { ok: false, jobId, error: { kind: 'reference_not_found', message: 'referenceAssetId does not exist for this character' } };
    }
    const local = localPathOf(ref);
    if (!local || !existsSync(local)) {
      return { ok: false, jobId, error: { kind: 'reference_not_local', message: 'reference asset has no locally-stored file to use as a reference' } };
    }
    referenceImagePath = local;
  }

  const width = input.width ?? 1080;
  const height = input.height ?? 1920;
  const outputPath = outputPathFor(deps.storage.storageDir, input.characterId, jobId, 'jpg');
  const request = { prompt: input.prompt, width, height, outputPath, referenceImagePath };

  const estimate = deps.providers.image.estimateImageCost(request);
  const auth = deps.ledger.authorize(estimate, input.characterId, deps.characterBudgetUsd);
  if (!auth.ok) {
    return { ok: false, jobId, error: { kind: 'budget_refused', message: auth.reason ?? 'refused before a paid call' } };
  }

  try {
    const result = await deps.providers.image.generateImage(request);
    const entry = deps.ledger.record({
      runId: jobId,
      character: input.characterId,
      provider: result.provider,
      model: result.model,
      operation: 'image',
      status: 'succeeded',
      unit: result.unit,
      quantity: result.quantity,
      unitCostUsd: result.unitCostUsd,
      estimatedCostUsd: result.estimatedCostUsd,
    });
    // The adapter may rename the file to its true format (e.g. .png); persist
    // whatever path it actually wrote.
    const storageKey = toStorageKey(deps.storage, result.outputPath);
    const asset = await createVisualAsset(db, {
      characterId: input.characterId,
      visualIdentityId: identity.id,
      kind: 'generated',
      status: input.status ?? GENERATED_ASSET_STATUS,
      contentRating: input.contentRating ?? 'sfw',
      requirementKey: input.requirementKey ?? null,
      storageKey,
      provenance: {
        jobId,
        mediaType: 'image',
        prompt: input.prompt,
        provider: result.provider,
        model: result.model,
        referenceAssetId: input.referenceAssetId ?? null,
        width,
        height,
        estimatedCostUsd: result.estimatedCostUsd,
        storagePath: result.outputPath,
        generatedAt: new Date().toISOString(),
      },
    });
    return { ok: true, jobId, asset, cost: { estimatedCostUsd: result.estimatedCostUsd, cumulativeUsd: entry.cumulativeUsd } };
  } catch (err) {
    // A failed paid attempt still costs its estimate — record it, never crash.
    deps.ledger.record({
      runId: jobId,
      character: input.characterId,
      provider: deps.providers.image.name,
      model: deps.providers.image.imageModel,
      operation: 'image',
      status: 'failed',
      unit: 'image',
      quantity: 1,
      unitCostUsd: estimate,
      estimatedCostUsd: estimate,
    });
    return { ok: false, jobId, error: errorFrom(err) };
  }
}

/**
 * Generate one short image-to-video clip from a source image asset and persist
 * it as a generated visual asset linked to the same character + identity version.
 * The rating is inherited from the source asset unless the request overrides it.
 */
export async function generateVideoJob(
  db: Db,
  deps: MediaJobDeps,
  input: GenerateVideoInput,
): Promise<MediaJobResult> {
  const jobId = randomUUID();

  const source = await getVisualAssetById(db, input.sourceImageAssetId);
  if (!source || source.characterId !== input.characterId) {
    return { ok: false, jobId, error: { kind: 'source_not_found', message: 'sourceImageAssetId does not exist for this character' } };
  }
  const referenceImagePath = localPathOf(source);
  if (!referenceImagePath || !existsSync(referenceImagePath)) {
    return { ok: false, jobId, error: { kind: 'source_file_missing', message: 'source image asset has no locally-stored file to animate' } };
  }

  const durationSeconds = input.durationSeconds ?? 5;
  const resolution = input.resolution ?? '720p';
  const outputPath = outputPathFor(deps.storage.storageDir, input.characterId, jobId, 'mp4');
  const request = { referenceImagePath, prompt: input.motionPrompt, durationSeconds, resolution, outputPath };

  const estimate = deps.providers.video.estimateVideoCost(request);
  const auth = deps.ledger.authorize(estimate, input.characterId, deps.characterBudgetUsd);
  if (!auth.ok) {
    return { ok: false, jobId, error: { kind: 'budget_refused', message: auth.reason ?? 'refused before a paid call' } };
  }

  try {
    const result = await deps.providers.video.imageToVideo(request);
    const entry = deps.ledger.record({
      runId: jobId,
      character: input.characterId,
      provider: result.provider,
      model: result.model,
      operation: 'video',
      status: 'succeeded',
      unit: result.unit,
      quantity: result.quantity,
      unitCostUsd: result.unitCostUsd,
      estimatedCostUsd: result.estimatedCostUsd,
    });
    const storageKey = toStorageKey(deps.storage, result.outputPath);
    // Link to the SOURCE asset's identity version so the clip stays with the
    // still it was derived from.
    const asset = await createVisualAsset(db, {
      characterId: input.characterId,
      visualIdentityId: source.visualIdentityId,
      kind: 'generated',
      status: input.status ?? GENERATED_ASSET_STATUS,
      contentRating: input.contentRating ?? (source.contentRating as ContentRating),
      requirementKey: input.requirementKey ?? null,
      storageKey,
      provenance: {
        jobId,
        mediaType: 'video',
        motionPrompt: input.motionPrompt,
        provider: result.provider,
        model: result.model,
        sourceImageAssetId: input.sourceImageAssetId,
        durationSeconds,
        resolution,
        estimatedCostUsd: result.estimatedCostUsd,
        storagePath: result.outputPath,
        generatedAt: new Date().toISOString(),
      },
    });
    return { ok: true, jobId, asset, cost: { estimatedCostUsd: result.estimatedCostUsd, cumulativeUsd: entry.cumulativeUsd } };
  } catch (err) {
    deps.ledger.record({
      runId: jobId,
      character: input.characterId,
      provider: deps.providers.video.name,
      model: deps.providers.video.videoModel,
      operation: 'video',
      status: 'failed',
      unit: 'second',
      quantity: durationSeconds,
      unitCostUsd: estimate / durationSeconds,
      estimatedCostUsd: estimate,
    });
    return { ok: false, jobId, error: errorFrom(err) };
  }
}
